const colorObject = {
  Confused: '#8A2BE2', // Blue Violet (Curiosity)
  Enchanted: '#FF1493', // Deep Pink (Love)
  Joyful: '#FFD700', // Gold (Joy)
  Disoriented: '#FF4500', // Orange Red (Fear)
  Tortured: '#DC143C', // Crimson (Anger)
  Determined: '#4682B4', // Steel Blue (Trust)
  Relaxed: '#00FA9A', // Medium Spring Green (Calm)
  Energetic: '#FFA500', // Orange (Anticipation)
  Peaceful: '#00FA9A', // Medium Spring Green (Calm)
  Hopeful: '#4682B4', // Steel Blue (Trust)
  Anxious: '#FF4500', // Orange Red (Fear)
  Excited: '#FFD700', // Gold (Joy)
  Content: '#00FA9A', // Medium Spring Green (Calm)
  Frustrated: '#DC143C', // Crimson (Anger)
  Curious: '#8A2BE2', // Blue Violet (Curiosity)
  Amused: '#FFD700', // Gold (Joy)
  Lonely: '#1E90FF', // Dodger Blue (Sadness)
  Loved: '#FF1493', // Deep Pink (Love)
  Sad: '#1E90FF', // Dodger Blue (Sadness)
  Angry: '#DC143C', // Crimson (Anger)
  Inspired: '#4682B4', // Steel Blue (Trust)
  Proud: '#FFD700', // Gold (Joy)
  Surprised: '#FF69B4', // Hot Pink (Surprise)
  Confident: '#4682B4', // Steel Blue (Trust)
  Grateful: '#FFD700', // Gold (Joy)
  Optimistic: '#FFD700', // Gold (Joy)
  Apathetic: '#A9A9A9', // Dark Gray (Boredom)
  Nostalgic: '#1E90FF', // Dodger Blue (Sadness)
  Intrigued: '#8A2BE2', // Blue Violet (Curiosity)
  Insecure: '#FF4500', // Orange Red (Fear)
  Courageous: '#4682B4', // Steel Blue (Trust)
  Overwhelmed: '#FF4500', // Orange Red (Fear)
  Playful: '#FFD700', // Gold (Joy)
  Regretful: '#1E90FF', // Dodger Blue (Sadness)
  Calm: '#00FA9A', // Medium Spring Green (Calm)
  Melancholic: '#1E90FF', // Dodger Blue (Sadness)
  Cautious: '#FF4500', // Orange Red (Fear)
  Reckless: '#DC143C', // Crimson (Anger)
  Humble: '#4682B4', // Steel Blue (Trust)
  Bored: '#A9A9A9', // Dark Gray (Boredom)
  Indifferent: '#A9A9A9', // Dark Gray (Boredom)
  Worried: '#FF4500', // Orange Red (Fear)
  Guilty: '#DC143C', // Crimson (Anger)
  Smitten: '#FF1493', // Deep Pink (Love)
  Tense: '#FF4500', // Orange Red (Fear)
  Patient: '#4682B4', // Steel Blue (Trust)
  Distracted: '#8A2BE2', // Blue Violet (Curiosity)
  Mischievous: '#FFD700', // Gold (Joy)
  Skeptical: '#8A2BE2', // Blue Violet (Curiosity)
  Ecstatic: '#FFD700', // Gold (Joy)
  Vulnerable: '#FF4500', // Orange Red (Fear)
  Apprehensive: '#FF4500', // Orange Red (Fear)
  Silly: '#FFD700', // Gold (Joy)
  Hopeless: '#1E90FF', // Dodger Blue (Sadness)
  Fascinated: '#8A2BE2', // Blue Violet (Curiosity)
  Eager: '#FFD700', // Gold (Joy)
  Bashful: '#FF1493', // Deep Pink (Love)
  Awkward: '#8A2BE2', // Blue Violet (Curiosity)
  Innocent: '#FF1493', // Deep Pink (Love)
  Gloomy: '#1E90FF', // Dodger Blue (Sadness)
  Giddy: '#FFD700', // Gold (Joy)
  Drowsy: '#A9A9A9', // Dark Gray (Boredom)
  Thrilled: '#FF69B4', // Hot Pink (Surprise)
  Doubtful: '#FF4500', // Orange Red (Fear)
  Mysterious: '#8A2BE2', // Blue Violet (Curiosity)
  Discontent: '#1E90FF', // Dodger Blue (Sadness)
  Enraged: '#DC143C', // Crimson (Anger)
  Serene: '#00FA9A', // Medium Spring Green (Calm)
  Horrified: '#FF4500', // Orange Red (Fear)
  Disgusted: '#32CD32', // Lime Green (Disgust)
  Curmudgeonly: '#DC143C', // Crimson (Anger)
  Lethargic: '#A9A9A9', // Dark Gray (Boredom)
  Cranky: '#DC143C', // Crimson (Anger)
  Envious: '#32CD32', // Lime Green (Disgust)
  Jittery: '#FF4500', // Orange Red (Fear)
  Nonchalant: '#A9A9A9', // Dark Gray (Boredom)
  Satisfied: '#00FA9A', // Medium Spring Green (Calm)
  Pensive: '#1E90FF', // Dodger Blue (Sadness)
  Restless: '#FF4500', // Orange Red (Fear)
  Perplexed: '#8A2BE2', // Blue Violet (Curiosity)
  Grumpy: '#DC143C', // Crimson (Anger)
  Shy: '#FF1493', // Deep Pink (Love)
  Elated: '#FFD700', // Gold (Joy)
  Fearful: '#FF4500', // Orange Red (Fear)
  Vexed: '#DC143C', // Crimson (Anger)
  Frozen: '#FF4500', // Orange Red (Fear)
  Amazed: '#FF69B4', // Hot Pink (Surprise)
  Nervous: '#FF4500', // Orange Red (Fear)
  Compassionate: '#FF1493', // Deep Pink (Love)
};