type DreamTopics = {
    [key: number]: string;
};

 const dreamTopics: DreamTopics = {
    1: "Flying in the sky",
    2: "Falling from great heights",
    3: "Being chased by something",
    4: "Meeting a famous person",
    5: "Being in a haunted house",
    6: "Winning the lottery",
    7: "Losing your teeth",
    8: "Riding a unicorn",
    9: "Swimming with dolphins",
    10: "Exploring a mysterious forest",
    11: "Traveling to space",
    12: "Becoming invisible",
    13: "Time traveling to the past",
    14: "Getting lost in a maze",
    15: "Talking to animals",
    16: "Attending a magical school",
    17: "Living in a post-apocalyptic world",
    18: "Solving a murder mystery",
    19: "Discovering hidden treasure",
    20: "Becoming a superhero",
    21: "Being a detective",
    22: "Dancing in the rain",
    23: "Having superpowers",
    24: "Escaping from a locked room",
    25: "Meeting your future self",
    26: "Battling mythical creatures",
    27: "Losing all my investments",
    28: "Visiting an underwater city",
    29: "Participating in a talent show",
    30: "Witnessing a volcano eruption",
    31: "Surviving a zombie apocalypse",
    32: "Being a pirate on a ship",
    33: "Finding a secret passage",
    34: "Solving a riddle",
    35: "Exploring a haunted cemetery",
    36: "Having a conversation with a robot",
    37: "Competing in a sports tournament",
    38: "Being a king or queen",
    39: "Winning a gold medal",
    40: "Going on a magical quest",
    41: "Experiencing a tornado",
    42: "Becoming a rock star",
    43: "Living in a fairy tale castle",
    44: "Going on a road trip",
    45: "Riding a dragon",
    46: "Meeting aliens from another planet",
    47: "Solving a math puzzle",
    48: "Traveling through time and space",
    49: "Escaping from a dragon's lair",
    50: "Visiting a parallel universe",
    51: "Battling evil witches",
    52: "Becoming a famous artist",
    53: "Going on a treasure hunt",
    54: "Discovering a hidden island",
    55: "Solving a crime as a detective",
    56: "Competing in a cooking competition",
    57: "Being a master chef",
    58: "Surviving a desert island",
    59: "Meeting a mermaid",
    60: "Going on a jungle adventure",
    61: "Becoming a race car driver",
    62: "Traveling through a wormhole",
    63: "Battling a giant monster",
    64: "Discovering a lost civilization",
    65: "Solving a space mystery",
    66: "Being a secret agent",
    67: "Going on a wild safari",
    68: "Exploring an enchanted forest",
    69: "Meeting a talking animal",
    70: "Becoming a famous writer",
    71: "Winning a dance competition",
    72: "Participating in a magic show",
    73: "Going on a deep-sea expedition",
    74: "Solving a supernatural mystery",
    75: "Being a time traveler",
    76: "Competing in a cooking show",
    77: "Visiting a hidden temple",
    78: "Discovering a new planet",
    79: "Battling alien invaders",
    80: "Exploring an ancient tomb",
    81: "Meeting a wise old sage",
    82: "Traveling to a distant galaxy",
    83: "Being a famous actor",
    84: "Winning an adventure race",
    85: "Escaping from a prison",
    86: "Solving a historical puzzle",
    87: "Battling a sea serpent",
    88: "Discovering a lost city",
    89: "Becoming a master magician",
    90: "Going on a space odyssey",
    91: "Meeting a legendary hero",
    92: "Participating in a reality TV show",
    93: "Being a professional athlete",
    94: "Winning a survival competition",
    95: "Solving a time paradox",
    96: "Traveling through a black hole",
    97: "Battling a mythical beast",
    98: "Discovering an ancient artifact",
    99: "Becoming a legendary explorer",
    100: "Going on an epic journey",
};